name: Semgrep Scan
run-name: Semgrep Scan
on: [push]
jobs:
  Semgrep_Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install Semgrep
        run: |
          python3 -m pip install semgrep
          semgrep --version
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Executes Semgrep
        run: |
          semgrep --config "p/security-audit" --include "sql" --metrics=off --json -o semgrep_report.json /home/runner/work/Vulnerable-Web-Application/Vulnerable-Web-Application
      - name: Persist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep_report
          path: semgrep_report.json
