name: Semgrep Scan
run-name: Semgrep Scan
on: [push]
jobs:
  Semgrep_Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install Semgrep
        run: |
          python3 -m pip install semgrep
          semgrep --version
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Executes Semgrep
        run: |
          ls -la
          pwd
          semgrep ci
